force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description>Collection of dogs</description>
    <label>Dog</label>
    <nameField>
        <label>Dog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>What stage of life is the dog?</description>
    <label>Age</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baby</fullName>
            </value>
            <value>
                <fullName>Young</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>What kind of dog is it?</description>
    <label>Breed</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <description>URL of dog image</description>
    <label>Image URL</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <description>Which parts?</description>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Shelter__c.field-meta.xml
<CustomField>
    <fullName>Shelter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shelter information</description>
    <label>Shelter</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dogs</relationshipLabel>
    <relationshipName>Dogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DogApi.cls
public with sharing class DogApi {

    @AuraEnabled(cacheable=true)
    public static String getBreeds() {
        String api = 'https://dog.ceo/api/breeds/list/all';
        HttpRequest req = new HttpRequest();
        req.setEndpoint(api);
        req.setMethod('GET');
        Http http = new Http();
        HTTPResponse res = http.send(req);

        return res.getBody();
    }

    @AuraEnabled(cacheable=true)
    public static String getImagesByBreed(String breedName) {
        String api = 'https://dog.ceo/api/breed/'+ breedName +'/images';
        HttpRequest req = new HttpRequest();
        req.setEndpoint(api);
        req.setMethod('GET');
        Http http = new Http();
        HTTPResponse res = http.send(req);

        return res.getBody();
    }

    @AuraEnabled(cacheable=true)
    public static String getDogs() {
        List<Dog__c> dogs = [
            SELECT Id, Name, Age__c, Breed__c, Sex__c, Shelter__c, Description__c, Image_URL__c
            FROM Dog__c
            LIMIT 15
        ];

        List<DogMsg> dogMsgList = new List<DogMsg>();

        for (Dog__c d : dogs) {
            String shelterName = getShelterName(d.Shelter__c);
            dogMsgList.add(new DogMsg(d, shelterName));
        }

        return JSON.serialize(dogMsgList);
    }

    private static String getShelterName(Id recordId) {
        Account act = [
            SELECT Id, Name
            FROM Account
            WHERE Id = :recordId
            LIMIT 1
        ];

        return act.Name;
    }

}