force-app/main/default/objects/Dog__c/Dog__c.object-meta.xml
<CustomObject>
    <description>Collection of dogs</description>
    <label>Dog</label>
    <nameField>
        <label>Dog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dog__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>What stage of life is the dog?</description>
    <label>Age</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baby</fullName>
            </value>
            <value>
                <fullName>Young</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>What kind of dog is it?</description>
    <label>Breed</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <description>URL of dog image</description>
    <label>Image URL</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dog__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <description>Which parts?</description>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DogMsg.cls
public with sharing class DogMsg {
    
    @AuraEnabled public Id id;
    @AuraEnabled public String name;
    @AuraEnabled public String age;
    @AuraEnabled public String breed;
    @AuraEnabled public String description;
    @AuraEnabled public String sex;
    @AuraEnabled public String shelter;
    @AuraEnabled public String imageURL;

    public DogMsg(Dog__c d, String shelterName) {
        this.id = d.Id;
        this.name = d.Name;
        this.age = d.Age__c;
        this.breed = d.Breed__c;
        this.description = d.Description__c;
        this.sex = d.Sex__c;
        this.shelter = shelterName;
        this.imageURL = d.Image_URL__c;
    }

}